<template>
    <div>
        <v-card flat>
            <v-card-title class="subtitle-1">
                Input Arguments
            </v-card-title>

            <v-card-text>
                <variables-field
                        :label="'Client Secret'"
                        :hint="'Client app secret. (generated by the provider)'"
                        :value.sync="value.property.clientsecret"
                ></variables-field>

                <variables-field
                        :label="'Response Url'"
                        :hint="'The final URL containing the authorization cod found in the address bar after authenticating and authorizing the Client app through the authorization URL'"
                        :value.sync="value.property.responseurl"
                ></variables-field>
     
            </v-card-text>
            
        <return-values-field
                :value.sync="value.property.token"
        ></return-values-field>

        </v-card>
    </div>
</template>

<script lang="ts">
    import { Component, Mixins } from "vue-property-decorator"
    import KeywordPanel from '../../panels/KeywordPanel.vue'

    @Component({
        components: {
            KeywordPanel,
        }
    })
    
    export default class GetOauthTokenPanel extends Mixins(KeywordPanel) {
    }
</script>