<template>
    <div>
        <v-card flat>
            <v-card-title class="subtitle-1">
                Input Arguments
            </v-card-title>

            <v-card-text>
                <variables-field
                        :label="'Client Id'"
                        :hint="'Client app ID. (generated by the provider)'"
                        :value.sync="value.property.client_id"
                        :required="true"
                ></variables-field>
            </v-card-text>
        </v-card>

        <return-values-field
                :value.sync="value.property.returnVal"
        ></return-values-field>
    </div>
</template>

<script lang="ts">
    import { Component, Mixins } from "vue-property-decorator"
    import KeywordPanel from '../../panels/KeywordPanel.vue'

    @Component({
        components: {
            KeywordPanel,
        }
    })
    
    export default class GenerateOauthUrlPanel extends Mixins(KeywordPanel) {
        mounted() {
            var description = "Generate an authorization URL which must be opened by the user to start the OAuth2 flow and obtain an authorization code as response."
            this.$emit("setDescription", description)
        }
    }
</script>