<template>
    <div>
        <v-card flat>
            <v-card-title class="subtitle-1">
                Input Arguments
            </v-card-title>

            <v-card-text>
                <variables-field
                        :label="'Client Id'"
                        :hint="'Client app ID. (generated by the provider)'"
                        :value.sync="value.property.client_id"
                        :required="true"
                ></variables-field>

                <variables-field
                        :label="'Client Secret'"
                        :hint="'Client app secret. (generated by the provider)'"
                        :value.sync="value.property.client_secret"
                        :required="true"
                ></variables-field>

                <variables-field
                        :label="'Token'"
                        :hint="'Full token dictionary previously obtained with Get Oauth Token'"
                        :value.sync="value.property.token"
                        :required="true"
                ></variables-field>
            </v-card-text>
        </v-card>
        
        <return-values-field
                :value.sync="value.property.returnVal"
        ></return-values-field>
    </div>
</template>

<script lang="ts">
    import { Component, Mixins } from "vue-property-decorator"
    import KeywordPanel from '../../panels/KeywordPanel.vue'

    @Component({
        components: {
            KeywordPanel,
        }
    })
    
    export default class RefreshOauthTokenPanel extends Mixins(KeywordPanel) {
    }
</script>