<template>
    <div>
        <v-card flat>
            <v-card-title class="subtitle-1">
                Input Arguments
            </v-card-title>

            <v-card-text>
                <variables-field
                        :label="'Client Id'"
                        :hint="'Client app ID. (generated by the provider)'"
                        :value.sync="value.property.client_id"
                ></variables-field>

                <variables-field
                        :label="'Client Secret'"
                        :hint="'Client app secret. (generated by the provider)'"
                        :value.sync="value.property.client_secret"
                ></variables-field>

                <variables-field
                        :label="'Token'"
                        :hint="'Full token dictionary previously obtained with Get Oauth Token'"
                        :value.sync="value.property.token"
                ></variables-field>


     
            </v-card-text>
            
        <return-values-field
                :value.sync="value.property.returnVal"
        ></return-values-field>

        </v-card>
    </div>
</template>

<script lang="ts">
    import { Component, Mixins } from "vue-property-decorator"
    import KeywordPanel from '../../panels/KeywordPanel.vue'

    @Component({
        components: {
            KeywordPanel,
        }
    })
    
    export default class RefreshOauthTokenPanel extends Mixins(KeywordPanel) {
        mounted() {
            var description = "Refreshes the token as the access one usually expires after 1h and the refresh one never expires.(as long as it doesn't get revoked)"
            this.$emit("setDescription", description)
        }
    }
</script>